language: node_js

os:
  - osx

node_js:
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

matrix:
  allow_failures:
    - node_js: "6"

before_script:
  - npm install -g mocha istanbul
script: npm test
